// Subcategory interface
export interface SubCategory {
  id: string;
  name: string;
}

// Main category interface
export interface MainCategory {
  id: string;
  name: string;
  subcategories: SubCategory[];
}

// All categories data – محدث بالكامل 2025
export const categories: MainCategory[] = [
  {
    id: "tech-general",
    name: "Industry-Agnostic Artificial Intelligence (AI) and Machine Learning (ML)",
    subcategories: [
      { id: "tg-1", name: "Blockchain" },
      { id: "tg-2", name: "Cloud Computing" },
      { id: "tg-3", name: "Cybersecurity" },
      { id: "tg-4", name: "Data Analytics" },
      { id: "tg-5", name: "Digital Transformation" },
      { id: "tg-6", name: "E-commerce" },
      { id: "tg-7", name: "Entrepreneurship" },
      { id: "tg-8", name: "Environmental Sustainability" },
      { id: "tg-9", name: "Global Market Trends" },
      { id: "tg-10", name: "Innovation" },
      { id: "tg-11", name: "Internet of Things (IoT)" },
      { id: "tg-12", name: "Networking" },
      { id: "tg-13", name: "Robotics" },
      { id: "tg-14", name: "Supply Chain Optimization" },
    ],
  },
  {
    id: "tech-specific",
    name: "Technology and Computing",
    subcategories: [
      { id: "ts-1", name: "5G and 6G" },
      { id: "ts-2", name: "Augmented Reality (AR) and Virtual Reality (VR)" },
      { id: "ts-3", name: "Autonomous Vehicles" },
      { id: "ts-4", name: "Big Data" },
      { id: "ts-5", name: "Cryptocurrency" },
      { id: "ts-6", name: "Gaming" },
      { id: "ts-7", name: "IT Infrastructure" },
      { id: "ts-8", name: "Quantum Computing" },
      { id: "ts-9", name: "Semiconductors" },
      { id: "ts-10", name: "Software Development" },
      { id: "ts-11", name: "Web Development" },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare and Medical",
    subcategories: [
      { id: "hc-1", name: "Biotechnology" },
      { id: "hc-2", name: "Dental Care" },
      { id: "hc-3", name: "Health Informatics" },
      { id: "hc-4", name: "Medical Devices" },
      { id: "hc-5", name: "Medical Imaging" },
      { id: "hc-6", name: "Pharmaceutical Technology" },
      { id: "hc-7", name: "Telemedicine" },
      { id: "hc-8", name: "Healthcare Management" },
      { id: "hc-9", name: "Medical Research" },
      { id: "hc-10", name: "Nutrition and Wellness" },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing and Industrial",
    subcategories: [
      { id: "man-1", name: "3D Printing" },
      { id: "man-2", name: "Automation" },
      { id: "man-3", name: "Aerospace" },
      { id: "man-4", name: "Automotive Technology" },
      { id: "man-5", name: "Building Materials" },
      { id: "man-6", name: "Chemical Engineering" },
      { id: "man-7", name: "Construction Equipment" },
      { id: "man-8", name: "Energy Efficiency" },
      { id: "man-9", name: "Industrial Robotics" },
      { id: "man-10", name: "Materials Science" },
      { id: "man-11", name: "Packaging Innovations" },
      { id: "man-12", name: "Process Automation" },
      { id: "man-13", name: "Quality Control" },
      { id: "man-14", name: "Renewable Energy" },
      { id: "man-15", name: "Smart Manufacturing" },
    ],
  },
  {
    id: "retail",
    name: "Retail and E-commerce",
    subcategories: [
      { id: "ret-1", name: "Customer Experience" },
      { id: "ret-2", name: "Digital Payments" },
      { id: "ret-3", name: "E-commerce Platforms" },
      { id: "ret-4", name: "Fashion Technology" },
      { id: "ret-5", name: "Inventory Management" },
      { id: "ret-6", name: "Logistics and Shipping" },
      { id: "ret-7", name: "Omnichannel Retailing" },
      { id: "ret-8", name: "Retail Marketing" },
      { id: "ret-9", name: "Store Design" },
      { id: "ret-10", name: "Supply Chain Management" },
    ],
  },
  {
    id: "foodbev",
    name: "Food and Beverage",
    subcategories: [
      { id: "fb-1", name: "Agricultural Technology" },
      { id: "fb-2", name: "Beverage Manufacturing" },
      { id: "fb-3", name: "Food Processing" },
      { id: "fb-4", name: "Food Safety" },
      { id: "fb-5", name: "Hospitality Management" },
      { id: "fb-6", name: "Nutrition and Wellness" },
      { id: "fb-7", name: "Organic and Specialty Foods" },
      { id: "fb-8", name: "Packaging Innovations" },
      { id: "fb-9", name: "Restaurant Technology" },
      { id: "fb-10", name: "Sustainable Agriculture" },
    ],
  },
  {
    id: "automotive",
    name: "Automotive and Transportation",
    subcategories: [
      { id: "at-1", name: "Autonomous Vehicles" },
      { id: "at-2", name: "Electric Vehicles (EVs)" },
      { id: "at-3", name: "Automotive Design" },
      { id: "at-4", name: "Car Safety" },
      { id: "at-5", name: "Connected Cars" },
      { id: "at-6", name: "Drone Technology" },
      { id: "at-7", name: "Fuel Efficiency" },
      { id: "at-8", name: "Infrastructure Development" },
      { id: "at-9", name: "Logistics and Transportation" },
      { id: "at-10", name: "Smart Traffic Management" },
    ],
  },
  {
    id: "fashion",
    name: "Fashion and Apparel",
    subcategories: [
      { id: "fa-1", name: "Fashion Design" },
      { id: "fa-2", name: "Fashion Technology" },
      { id: "fa-3", name: "Luxury Goods" },
      { id: "fa-4", name: "Sustainable Fashion" },
      { id: "fa-5", name: "Textile Manufacturing" },
      { id: "fa-6", name: "Apparel Production" },
      { id: "fa-7", name: "Fashion Marketing" },
      { id: "fa-8", name: "Retail Management" },
      { id: "fa-9", name: "Beauty and Cosmetics" },
      { id: "fa-10", name: "Accessories" },
    ],
  },
  {
    id: "construction",
    name: "Construction and Architecture",
    subcategories: [
      { id: "con-1", name: "Building Information Modeling (BIM)" },
      { id: "con-2", name: "Construction Equipment" },
      { id: "con-3", name: "Green Building" },
      { id: "con-4", name: "Interior Design" },
      { id: "con-5", name: "Landscape Architecture" },
      { id: "con-6", name: "Materials Science" },
      { id: "con-7", name: "Smart Buildings" },
      { id: "con-8", name: "Sustainable Architecture" },
      { id: "con-9", name: "Urban Planning" },
      { id: "con-10", name: "Architecture Software" },
    ],
  },
  {
    id: "energy",
    name: "Energy and Environment",
    subcategories: [
      { id: "en-1", name: "Renewable Energy (Solar, Wind, Hydro)" },
      { id: "en-2", name: "Energy Efficiency" },
      { id: "en-3", name: "Environmental Sustainability" },
      { id: "en-4", name: "Green Technology" },
      { id: "en-5", name: "Climate Change Solutions" },
      { id: "en-6", name: "Carbon Capture" },
      { id: "en-7", name: "Sustainable Infrastructure" },
      { id: "en-8", name: "Eco-Friendly Products" },
      { id: "en-9", name: "Waste Management" },
      { id: "en-10", name: "Water Conservation" },
    ],
  },
  {
    id: "education",
    name: "Education and Training",
    subcategories: [
      { id: "ed-1", name: "EdTech" },
      { id: "ed-2", name: "Online Learning Platforms" },
      { id: "ed-3", name: "Educational Software" },
      { id: "ed-4", name: "Teaching Methods" },
      { id: "ed-5", name: "Special Education" },
      { id: "ed-6", name: "Career Development" },
      { id: "ed-7", name: "Professional Training" },
      { id: "ed-8", name: "Language Learning" },
      { id: "ed-9", name: "STEM Education" },
      { id: "ed-10", name: "Virtual Reality Training" },
    ],
  },
  {
    id: "arts",
    name: "Arts and Entertainment",
    subcategories: [
      { id: "art-1", name: "Animation" },
      { id: "art-2", name: "Film Production" },
      { id: "art-3", name: "Gaming" },
      { id: "art-4", name: "Graphic Design" },
      { id: "art-5", name: "Music Technology" },
      { id: "art-6", name: "Photography" },
      { id: "art-7", name: "Visual Effects" },
      { id: "art-8", name: "Virtual Reality Experiences" },
      { id: "art-9", name: "Augmented Reality Art" },
      { id: "art-10", name: "Digital Media" },
    ],
  },
  {
    id: "travel",
    name: "Travel and Hospitality",
    subcategories: [
      { id: "tr-1", name: "Hotel Management" },
      { id: "tr-2", name: "Travel Technology" },
      { id: "tr-3", name: "Tourism Marketing" },
      { id: "tr-4", name: "Destination Management" },
      { id: "tr-5", name: "Event Planning" },
      { id: "tr-6", name: "Restaurant Management" },
      { id: "tr-7", name: "Hospitality Software" },
      { id: "tr-8", name: "Travel Apps" },
      { id: "tr-9", name: "Luxury Travel" },
      { id: "tr-10", name: "Sustainable Tourism" },
    ],
  },
  {
    id: "agriculture",
    name: "Agriculture",
    subcategories: [
      { id: "ag-1", name: "Agricultural Technology" },
      { id: "ag-2 2", name: "Farm Equipment" },
      { id: "ag-3", name: "Crop Management" },
      { id: "ag-4", name: "Livestock Production" },
      { id: "ag-5", name: "Precision Agriculture" },
      { id: "ag-6", name: "Organic Farming" },
      { id: "ag-7", name: "Sustainable Agriculture" },
      { id: "ag-8", name: "Irrigation Systems" },
      { id: "ag-9", name: "Farm Automation" },
      { id: "ag-10", name: "Agricultural Research" },
    ],
  },
  {
    id: "government",
    name: "Government and Public Sector",
    subcategories: [
      { id: "gov-1", name: "Cybersecurity" },
      { id: "gov-2", name: "Digital Governance" },
      { id: "gov-3", name: "Emergency Response" },
      { id: "gov-4", name: "Government IT" },
      { id: "gov-5", name: "Public Health" },
      { id: "gov-6", name: "Smart Cities" },
      { id: "gov-7", name: "Transportation Infrastructure" },
      { id: "gov-8", name: "Urban Planning" },
      { id: "gov-9", name: "Waste Management" },
      { id: "gov-10", name: "Water Conservation" },
    ],
  },
  {
    id: "realestate",
    name: "Real Estate",
    subcategories: [
      { id: "re-1", name: "Property Management" },
      { id: "re-2", name: "Real Estate Marketing" },
      { id: "re-3", name: "Building Design" },
      { id: "re-4", name: "Architecture Software" },
      { id: "re-5", name: "Construction Management" },
      { id: "re-6", name: "Smart Homes" },
      { id: "re-7", name: "Sustainable Building" },
      { id: "re-8", name: "Urban Planning" },
      { id: "re-9", name: "Property Technology" },
      { id: "re-10", name: "Real Estate Investment" },
    ],
  },

  // ================== أماكن فعلية (Places) ==================
  {
    id: "places-residential",
    name: "Residential (Accommodations)",
    subcategories: [
      { id: "pr-1", name: "Standard residential apartment" },
      { id: "pr-2", name: "Serviced apartment (Aparthotel)" },
      { id: "pr-3", name: "Standalone villa" },
      { id: "pr-4", name: "Twin-house villa" },
      { id: "pr-5", name: "Luxury hotel (5-star)" },
      { id: "pr-6", name: "Budget hotel (2-3 stars)" },
      { id: "pr-7", name: "Boutique hotel (artistic design)" },
      { id: "pr-8", name: "Mountain chalet" },
      { id: "pr-9", name: "Beachfront chalet" },
      { id: "pr-10", name: "Traveler hostel" },
      { id: "pr-11", name: "Traditional heritage house" },
      { id: "pr-12", name: "University student housing" },
      { id: "pr-13", name: "Temporary worker accommodation" },
      { id: "pr-14", name: "Resort complex" },
      { id: "pr-15", name: "Mobile home (Caravan)" },
      { id: "pr-16", name: "Emergency shelter (homeless)" },
      { id: "pr-17", name: "Short-term rental (e.g., Airbnb)" },
      { id: "pr-18", name: "Royal palace" },
      { id: "pr-19", name: "Rural agritourism homestay" },
      { id: "pr-20", name: "Expatriate compound housing" },
    ],
  },
  {
    id: "places-healthcare",
    name: "Healthcare Facilities",
    subcategories: [
      { id: "ph-1", name: "General hospital" },
      { id: "ph-2", name: "Specialty hospital (cardiac, oncology)" },
      { id: "ph-3", name: "Dental clinic" },
      { id: "ph-4", name: "Dermatology clinic" },
      { id: "ph-5", name: "Women’s health & maternity clinic" },
      { id: "ph-6", name: "Ophthalmology clinic" },
      { id: "ph-7", name: "Pediatric clinic" },
      { id: "ph-8", name: "24/7 emergency center" },
      { id: "ph-9", name: "Blood testing lab" },
      { id: "ph-10", name: "Urine testing lab" },
      { id: "ph-11", name: "X-ray imaging center" },
      { id: "ph-12", name: "MRI/CT scan center" },
      { id: "ph-13", name: "Day pharmacy" },
      { id: "ph-14", name: "Night pharmacy" },
      { id: "ph-15", name: "Physiotherapy center" },
      { id: "ph-16", name: "Post-injury rehabilitation center" },
      { id: "ph-17", name: "Traditional cupping therapy center" },
      { id: "ph-18", name: "Therapeutic massage center" },
      { id: "ph-19", name: "Chinese medicine clinic (acupuncture)" },
      { id: "ph-20", name: "Clinical nutrition center" },
    ],
  },
  {
    id: "places-education",
    name: "Educational Institutions",
    subcategories: [
      { id: "pe-1", name: "Public university" },
      { id: "pe-2", name: "Private university" },
      { id: "pe-3", name: "Community college" },
      { id: "pe-4", name: "Public high school" },
      { id: "pe-5", name: "International high school" },
      { id: "pe-6", name: "Elementary school" },
      { id: "pe-7", name: "Kindergarten (ages 3-6)" },
      { id: "pe-8", name: "Nursery (under age 3)" },
      { id: "pe-9", name: "Language institute (English, French)" },
      { id: "pe-10", name: "Coding & tech training center" },
      { id: "pe-11", name: "Music conservatory" },
      { id: "pe-12", name: "Art studio (painting, sculpture)" },
      { id: "pe-13", name: "Online education hub" },
      { id: "pe-14", name: "Chemistry laboratory" },
      { id: "pe-15", name: "Physics laboratory" },
      { id: "pe-16", name: "Public library" },
      { id: "pe-17", name: "University library" },
      { id: "pe-18", name: "Scientific research center" },
      { id: "pe-19", name: "Vocational school (sewing, carpentry)" },
      { id: "pe-20", name: "Technical training center (electricity, plumbing)" },
    ],
  },
  {
    id: "places-transport",
    name: "Transportation Hubs",
    subcategories: [
      { id: "pt-1", name: "International airport" },
      { id: "pt-2", name: "Domestic airport" },
      { id: "pt-3", name: "High-speed rail station" },
      { id: "pt-4", name: "Conventional train station" },
      { id: "pt-5", name: "Metro/subway station" },
      { id: "pt-6", name: "Tram station" },
      { id: "pt-7", name: "Seaport (cruise ships)" },
      { id: "pt-8", name: "River port (ferries)" },
      { id: "pt-9", name: "Public bus terminal" },
      { id: "pt-10", name: "Taxi stand" },
      { id: "pt-11", name: "Gas station" },
      { id: "pt-12", name: "EV charging station" },
      { id: "pt-13", name: "Car rental agency" },
      { id: "pt-14", name: "Bicycle rental shop" },
      { id: "pt-15", name: "Helicopter pad" },
      { id: "pt-16", name: "Mountain cable car station" },
      { id: "pt-17", name: "E-scooter parking zone" },
      { id: "pt-18", name: "Aircraft maintenance center" },
      { id: "pt-19", name: "Train maintenance depot" },
      { id: "pt-20", name: "Ticket booking office (flights, trains)" },
    ],
  },
  {
    id: "places-shopping",
    name: "Shopping Venues",
    subcategories: [
      { id: "ps-1", name: "Traditional souk/market" },
      { id: "ps-2", name: "Night market" },
      { id: "ps-3", name: "Small grocery store" },
      { id: "ps-4", name: "Supermarket chain" },
      { id: "ps-5", name: "Shopping mall" },
      { id: "ps-6", name: "Electronics store" },
      { id: "ps-7", name: "Home appliances store" },
      { id: "ps-8", name: "Men’s clothing boutique" },
      { id: "ps-9", name: "Women’s fashion store" },
      { id: "ps-10", name: "Children’s store (clothes, toys)" },
      { id: "ps-11", name: "Accessories shop (watches, sunglasses)" },
      { id: "ps-12", name: "Perfume boutique" },
      { id: "ps-13", name: "Cosmetics store" },
      { id: "ps-14", name: "Sports equipment shop" },
      { id: "ps-15", name: "Stationery store" },
      { id: "ps-16", name: "Gift & souvenir shop" },
      { id: "ps-17", name: "Carpet & home décor store" },
      { id: "ps-18", name: "Office supplies store" },
      { id: "ps-19", name: "Building materials store" },
      { id: "ps-20", name: "Auto parts store" },
    ],
  },
  {
    id: "places-food",
    name: "Restaurants & Cafés",
    subcategories: [
      { id: "pf-1", name: "Fine dining restaurant (French/Italian)" },
      { id: "pf-2", name: "Local cuisine restaurant" },
      { id: "pf-3", name: "Fast-food chain (burger, pizza)" },
      { id: "pf-4", name: "Traditional Arabic coffeehouse" },
      { id: "pf-5", name: "Instagrammable modern café" },
      { id: "pf-6", name: "Asian cuisine restaurant (Japanese, Thai)" },
      { id: "pf-7", name: "Indian restaurant" },
      { id: "pf-8", name: "Organic/health food restaurant" },
      { id: "pf-9", name: "Vegan restaurant" },
      { id: "pf-10", name: "Seafood restaurant" },
      { id: "pf-11", name: "BBQ grill restaurant" },
      { id: "pf-12", name: "Middle Eastern dessert café" },
      { id: "pf-13", name: "Museum café" },
      { id: "pf-14", name: "Rooftop restaurant" },
      { id: "pf-15", name: "Hotel restaurant" },
      { id: "pf-16", name: "Food truck" },
      { id: "pf-17", name: "Artisanal ice cream parlor" },
      { id: "pf-18", name: "Cat café" },
      { id: "pf-19", name: "Quiet reading café" },
      { id: "pf-20", name: "Nightclub/bar" },
    ],
  },
  {
    id: "places-entertainment",
    name: "Entertainment & Events",
    subcategories: [
      { id: "pen-1", name: "Standard cinema" },
      { id: "pen-2", name: "IMAX/4D cinema" },
      { id: "pen-3", name: "Comedy theater" },
      { id: "pen-4", name: "Improv comedy club" },
      { id: "pen-5", name: "Water park" },
      { id: "pen-6", name: "Indoor amusement park" },
      { id: "pen-7", name: "Seasonal carnival" },
      { id: "pen-8", name: "Concert hall" },
      { id: "pen-9", name: "Dance festival venue" },
      { id: "pen-10", name: "Traditional circus" },
      { id: "pen-11", name: "Street performance plaza" },
      { id: "pen-12", name: "Video game expo center" },
      { id: "pen-13", name: "Escape room facility" },
      { id: "pen-14", name: "Licensed casino" },
      { id: "pen-15", name: "Bowling alley" },
      { id: "pen-16", name: "E-sports gaming lounge" },
      { id: "pen-17", name: "Children’s playground complex" },
      { id: "pen-18", name: "Illusion museum" },
      { id: "pen-19", name: "Cultural heritage nights (e.g., Ramadan)" },
      { id: "pen-20", name: "Family edutainment center (e.g., KidZania)" },
    ],
  },
  {
    id: "places-sports",
    name: "Sports & Fitness",
    subcategories: [
      { id: "psf-1", name: "Women-only gym" },
      { id: "psf-2", name: "Men-only gym" },
      { id: "psf-3", name: "Co-ed fitness center" },
      { id: "psf-4", name: "Football stadium" },
      { id: "psf-5", name: "Tennis court complex" },
      { id: "psf-6", name: "Auto racing track" },
      { id: "psf-7", name: "Scuba diving center" },
      { id: "psf-8", name: "Golf club" },
      { id: "psf-9", name: "Dedicated cycling path" },
      { id: "psf-10", name: "Night-lit jogging track" },
      { id: "psf-11", name: "Bodybuilding gym" },
      { id: "psf-12", name: "Aerial yoga studio" },
      { id: "psf-13", name: "Rock climbing gym" },
      { id: "psf-14", name: "Equestrian club" },
      { id: "psf-15", name: "Archery range" },
      { id: "psf-16", name: "Ice skating rink" },
      { id: "psf-17", name: "Olympic-sized swimming pool" },
      { id: "psf-18", name: "Basketball arena" },
      { id: "psf-19", name: "Table tennis hall" },
      { id: "psf-20", name: "Olympic athlete training center" },
    ],
  },
  {
    id: "places-tourism",
    name: "Tourism & Heritage",
    subcategories: [
      { id: "pto-1", name: "Pyramids & ancient structures" },
      { id: "pto-2", name: "Historic castles" },
      { id: "pto-3", name: "Archaeology museum" },
      { id: "pto-4", name: "Tourist beach" },
      { id: "pto-5", name: "Island resort" },
      { id: "pto-6", name: "Desert resort" },
      { id: "pto-7", name: "Heritage village" },
      { id: "pto-8", name: "Natural waterfall" },
      { id: "pto-9", name: "Tourist cave system" },
      { id: "pto-10", name: "Heritage walking trail" },
      { id: "pto-11", name: "Tourist market" },
      { id: "pto-12", name: "Historic bridge" },
      { id: "pto-13", name: "Religious tourism site" },
      { id: "pto-14", name: "Heritage train station" },
      { id: "pto-15", name: "Palace open to visitors" },
      { id: "pto-16", name: "Rare botanical garden" },
      { id: "pto-17", name: "Famous film location" },
      { id: "pto-18", name: "Literary landmark" },
      { id: "pto-19", name: "Night tourist market" },
      { id: "pto-20", name: "Desert safari camp" },
    ],
  },
  {
    id: "places-culture",
    name: "Culture & Arts",
    subcategories: [
      { id: "pc-1", name: "Opera house" },
      { id: "pc-2", name: "Experimental theater" },
      { id: "pc-3", name: "Fine arts museum" },
      { id: "pc-4", name: "Cinema museum" },
      { id: "pc-5", name: "Historic library" },
      { id: "pc-6", name: "Classical music hall" },
      { id: "pc-7", name: "Outdoor sculpture exhibition" },
      { id: "pc-8", name: "Community cultural center" },
      { id: "pc-9", name: "Art workshop (painting, pottery)" },
      { id: "pc-10", name: "Poetry festival venue" },
      { id: "pc-11", name: "Photography exhibition gallery" },
      { id: "pc-12", name: "Music education center" },
      { id: "pc-13", name: "Interactive children’s museum" },
      { id: "pc-14", name: "Local heritage cultural hub" },
      { id: "pc-15", name: "Cultural lecture hall" },
      { id: "pc-16", name: "Rare/academic library" },
      { id: "pc-17", name: "International book fair venue" },
      { id: "pc-18", name: "Cultural research institute" },
      { id: "pc-19", name: "Digital art museum" },
      { id: "pc-20", name: "Street art zone (graffiti, urban art)" },
    ],
  },
  {
    id: "places-religious",
    name: "Religious Sites",
    subcategories: [
      { id: "pre-1", name: "Historic mosque" },
      { id: "pre-2", name: "Modern mosque" },
      { id: "pre-3", name: "Catholic church" },
      { id: "pre-4", name: "Orthodox church" },
      { id: "pre-5", name: "Buddhist temple" },
      { id: "pre-6", name: "Hindu temple" },
      { id: "pre-7", name: "Protestant church" },
      { id: "pre-8", name: "Sikh gurdwara" },
      { id: "pre-9", name: "Sufi shrine (saints’ mausoleums)" },
      { id: "pre-10", name: "Coptic church" },
      { id: "pre-11", name: "Quran memorization center" },
      { id: "pre-12", name: "Meditation & spiritual retreat center" },
      { id: "pre-13", name: "Christian monastery" },
      { id: "pre-14", name: "Historic religious cemetery" },
      { id: "pre-15", name: "Ritual washing facility (Ghusl)" },
      { id: "pre-16", name: "Airport prayer room" },
      { id: "pre-17", name: "Hospital chapel" },
      { id: "pre-18", name: "Temple in shopping malls" },
      { id: "pre-19", name: "Interfaith dialogue center" },
      { id: "pre-20", name: "Specialized religious library" },
    ],
  },
  {
    id: "places-nature",
    name: "Nature & Outdoors",
    subcategories: [
      { id: "pn-1", name: "Urban public park" },
      { id: "pn-2", name: "Protected national park" },
      { id: "pn-3", name: "Dense forest reserve" },
      { id: "pn-4", name: "Desert adventure zone" },
      { id: "pn-5", name: "Mountain climbing area" },
      { id: "pn-6", name: "Sandy beach" },
      { id: "pn-7", name: "Rocky shoreline" },
      { id: "pn-8", name: "Artificial lake" },
      { id: "pn-9", name: "Natural freshwater lake" },
      { id: "pn-10", name: "Whitewater river rafting spot" },
      { id: "pn-11", name: "Waterfall viewpoint" },
      { id: "pn-12", name: "Exploratory cave system" },
      { id: "pn-13", name: "Birdwatching sanctuary" },
      { id: "pn-14", name: "Mountain biking trail" },
      { id: "pn-15", name: "Organized camping site" },
      { id: "pn-16", name: "Wild animal safari park" },
      { id: "pn-17", name: "Rare flower nursery" },
      { id: "pn-18", name: "Sea turtle conservation beach" },
      { id: "pn-19", name: "Licensed hunting reserve" },
      { id: "pn-20", name: "Hiking trail network" },
    ],
  },
  {
    id: "places-services",
    name: "Daily Services",
    subcategories: [
      { id: "pds-1", name: "Commercial bank branch" },
      { id: "pds-2", name: "Islamic finance institution" },
      { id: "pds-3", name: "Currency exchange office" },
      { id: "pds-4", name: "Laundry & dry-cleaning service" },
      { id: "pds-5", name: "Car wash center" },
      { id: "pds-6", name: "Men’s barbershop" },
      { id: "pds-7", name: "Women’s beauty salon" },
      { id: "pds-8", name: "Shoe repair workshop" },
      { id: "pds-9", name: "Electronics repair shop" },
      { id: "pds-10", name: "Home hardware store" },
      { id: "pds-11", name: "Post office" },
      { id: "pds-12", name: "Internet café" },
      { id: "pds-13", name: "Mobile phone store" },
      { id: "pds-14", name: "Furniture showroom" },
      { id: "pds-15", name: "Gift wrapping service" },
      { id: "pds-16", name: "Office supplies store" },
      { id: "pds-17", name: "Watch repair studio" },
      { id: "pds-18", name: "Florist shop" },
      { id: "pds-19", name: "Newsstand/book kiosk" },
      { id: "pds-20", name: "Carpet cleaning service" },
    ],
  },
  {
    id: "places-emergency",
    name: "Emergency & Relief",
    subcategories: [
      { id: "pe-1", name: "General police station" },
      { id: "pe-2", name: "Mobile police unit" },
      { id: "pe-3", name: "Firefighting headquarters" },
      { id: "pe-4", name: "Marine rescue team base" },
      { id: "pe-5", name: "Mountain rescue operations center" },
      { id: "pe-6", name: "Field hospital (disaster response)" },
      { id: "pe-7", name: "Natural disaster shelter" },
      { id: "pe-8", name: "Blood donation center" },
      { id: "pe-9", name: "Mobile ambulance unit" },
      { id: "pe-10", name: "24/7 emergency hotline center" },
      { id: "pe-11", name: "Homeless temporary shelter" },
      { id: "pe-12", name: "Forest firefighting base" },
      { id: "pe-13", name: "Earthquake monitoring station" },
      { id: "pe-14", name: "Hurricane warning center" },
      { id: "pe-15", name: "Animal rescue emergency unit" },
      { id: "pe-16", name: "Flood relief operations hub" },
      { id: "pe-17", name: "Disaster documentation center" },
      { id: "pe-18", name: "Emergency response training academy" },
      { id: "pe-19", name: "Food aid warehouse" },
      { id: "pe-20", name: "Post-disaster rehabilitation center" },
    ],
  },
];