export const properties = [
  {
    id: 1,
    title: "Luxury Appartment",
    image: "https://cdn.dubaiimmobilier.fr/wp-content/uploads/2024/06/Sky-High-Luxury.webp",
    price: "EGP 12.8K",
    beds: 1,
    baths: 2,
    size: 77.9,
    location: "Cairo",
    description: "Brand New Fully Furnished 1BR ...",
    category: "Apartment",
    date: "2024-01-15",
  },
  {
    id: 2,
    title: "Modern Villa",
    image: "https://cdn.dubaiimmobilier.fr/wp-content/uploads/2024/06/Sky-High-Luxury.webp",
    price: "EGP 25.5K",
    beds: 3,
    baths: 3,
    size: 150.0,
    location: "Alexandria",
    description: "Spacious Villa with Garden ...",
    category: "Villa",
    date: "2024-03-10",
  },
  {
    id: 3,
    title: "Downtown Studio",
    image: "https://cdn.dubaiimmobilier.fr/wp-content/uploads/2024/06/Sky-High-Luxury.webp",
    price: "EGP 8.5K",
    beds: 1,
    baths: 1,
    size: 45.0,
    location: "Cairo",
    description: "Cozy Studio in City Center ...",
    category: "Studio",
    date: "2024-05-02",
  },
  {
    id: 4,
    title: "Beach House",
    image: "https://cdn.dubaiimmobilier.fr/wp-content/uploads/2024/06/Sky-High-Luxury.webp",
    price: "EGP 35.0K",
    beds: 4,
    baths: 4,
    size: 200.0,
    location: "North Coast",
    description: "Stunning Beach House with Pool ...",
    category: "House",
    date: "2024-06-22",
  },
  {
    id: 5,
    title: "Penthouse Suite",
    image: "https://cdn.dubaiimmobilier.fr/wp-content/uploads/2024/06/Sky-High-Luxury.webp",
    price: "EGP 45.0K",
    beds: 3,
    baths: 3,
    size: 180.0,
    location: "New Cairo",
    description: "Exclusive Penthouse with View ...",
    category: "Penthouse",
    date: "2024-08-05",
  },
  {
    id: 6,
    title: "Family Apartment",
    image: "https://cdn.dubaiimmobilier.fr/wp-content/uploads/2024/06/Sky-High-Luxury.webp",
    price: "EGP 15.0K",
    beds: 2,
    baths: 2,
    size: 95.0,
    location: "Giza",
    description: "Comfortable 2BR for Families ...",
    category: "Apartment",
    date: "2024-09-12",
  },
  {
    id: 7,
    title: "Garden Villa",
    image: "https://cdn.dubaiimmobilier.fr/wp-content/uploads/2024/06/Sky-High-Luxury.webp",
    price: "EGP 28.0K",
    beds: 3,
    baths: 2,
    size: 160.0,
    location: "Cairo",
    description: "Villa with Beautiful Garden ...",
    category: "Villa",
    date: "2024-10-01",
  },
  {
    id: 8,
    title: "City Loft",
    image: "https://cdn.dubaiimmobilier.fr/wp-content/uploads/2024/06/Sky-High-Luxury.webp",
    price: "EGP 18.5K",
    beds: 2,
    baths: 2,
    size: 110.0,
    location: "Cairo",
    description: "Modern Loft in Downtown ...",
    category: "Loft",
    date: "2024-11-15",
  },
];
