import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/free-mode";
import LayoutWrapper from "./userportal/componants/LayoutWrapper";
import { AuthProvider } from "./providers/AuthContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TO NEXT STEP .",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster
          position="top-center" 
          richColors               
          closeButton              
          toastOptions={{
            duration: 4000,
           
          }}
        />
  <AuthProvider>{children}</AuthProvider> 
      </body>
    </html>
  );
}
