import type { Metadata } from "next";
import "./globals.css";

import LayoutWrapper from "./userportal/componants/LayoutWrapper";
import { AuthProvider } from "./providers/AuthContext";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "TO NEXT STEP .",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.bunny.net" />
      </head>
      <body className="antialiased">
        <Toaster
          position="top-center"
          richColors
          closeButton
          toastOptions={{ duration: 4000 }}
        />
        <AuthProvider>
         {children}
        </AuthProvider>
      </body>
    </html>
  );
}
